import type { RequiredDataFromCollectionSlug } from 'payload'

export const home: RequiredDataFromCollectionSlug<'pages'> = {
  slug: 'home',
  _status: 'published',
  hero: {
    type: 'highImpact',
    links: [
      {
        link: {
          type: 'custom',
          appearance: 'default',
          label: 'Explore Articles',
          url: '/posts',
        },
      },
      {
        link: {
          type: 'custom',
          appearance: 'outline',
          label: 'Watch Videos',
          url: '/#',
        },
      },
    ],
    // @ts-ignore
    media: '{{IMAGE_1}}',
    richText: {
      root: {
        type: 'root',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            tag: 'h1',
            type: 'heading',
            format: 'start',
            indent: 0,
            version: 1,
            children: [
              {
                mode: 'normal',
                text: 'Fixing Health',
                type: 'text',
                style: '',
                detail: 0,
                format: 0,
                version: 1,
              },
            ],
            direction: 'ltr',
          },
          {
            type: 'paragraph',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                mode: 'normal',
                text: 'Discover the latest insights, tips, and trends in health and wellness. Our diverse content covers articles, videos, podcasts, and more to help you live your healthiest life.',
                type: 'text',
                style: '',
                detail: 0,
                format: 0,
                version: 1,
              },
            ],
            direction: 'ltr',
            textFormat: 0,
          },
        ],
        direction: 'ltr',
      },
    },
  },
  layout: [
    {
      blockName: 'Content Block',
      columns: [
        {
          size: 'full',
          richText: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  tag: 'h2',
                  type: 'heading',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Explore Our Content',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  type: 'paragraph',
                  format: 'center',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'From in-depth articles to engaging videos and podcasts, we cover a wide range of health and wellness topics to help you live your best life.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  textFormat: 0,
                },
              ],
              direction: 'ltr',
            },
          },
          enableLink: null,
          link: {
            type: 'reference',
            newTab: null,
            url: null,
            label: null,
            appearance: 'default',
          },
        },
        {
          size: 'oneThird',
          richText: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  tag: 'h3',
                  type: 'heading',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Articles',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'In-depth written content covering a variety of health and wellness topics.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  textFormat: 0,
                },
              ],
              direction: 'ltr',
            },
          },
          enableLink: true,
          link: {
            type: 'custom',
            newTab: null,
            url: '/posts',
            label: 'Explore Articles',
            appearance: 'default',
          },
        },
        {
          size: 'oneThird',
          richText: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  tag: 'h3',
                  type: 'heading',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Videos',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Engaging video content to help you learn and stay motivated',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  textFormat: 0,
                },
              ],
              direction: 'ltr',
            },
          },
          enableLink: true,
          link: {
            type: 'custom',
            newTab: null,
            url: '/#',
            label: 'Watch Videos',
            appearance: 'default',
          },
        },
        {
          size: 'oneThird',
          richText: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  tag: 'h3',
                  type: 'heading',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Podcasts',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Listen to our experts discuss the latest health and wellness topics',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  textFormat: 0,
                },
              ],
              direction: 'ltr',
            },
          },
          enableLink: true,
          link: {
            type: 'custom',
            newTab: null,
            url: '/#',
            label: 'Listen to Podcasts',
            appearance: 'default',
          },
        },
        {
          size: 'oneThird',
          richText: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  tag: 'h3',
                  type: 'heading',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Analytics',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Drive into data-driven insights to improve your health and wellness.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  textFormat: 0,
                },
              ],
              direction: 'ltr',
            },
          },
          enableLink: true,
          link: {
            type: 'custom',
            newTab: null,
            url: '/#',
            label: 'Explore Analytics',
            appearance: 'default',
          },
        },
        {
          size: 'oneThird',
          richText: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  tag: 'h3',
                  type: 'heading',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Quizzes',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Test your knowledge and get personalized health recommendations.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  textFormat: 0,
                },
              ],
              direction: 'ltr',
            },
          },
          enableLink: true,
          link: {
            type: 'custom',
            newTab: null,
            url: '/#',
            label: 'Take a Quiz',
            appearance: 'default',
          },
        },
        {
          size: 'oneThird',
          richText: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  tag: 'h3',
                  type: 'heading',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Community',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Connect with like-minded individuals and experts in our vibrant community.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  textFormat: 0,
                },
              ],
              direction: 'ltr',
            },
          },
          enableLink: true,
          link: {
            type: 'custom',
            newTab: null,
            url: '/#',
            label: 'Join the Community',
            appearance: 'default',
          },
        },
      ],
      blockType: 'content',
    },
    {
      introContent: {
        root: {
          type: 'root',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              tag: 'h3',
              type: 'heading',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Recent Articles',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
            },
            {
              type: 'paragraph',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Check out our latest articles covering a variety of health and wellness topics.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textFormat: 0,
            },
          ],
          direction: 'ltr',
        },
      },
      populateBy: 'collection',
      relationTo: 'posts',
      limit: 10,
      blockName: 'Archive Block',
      blockType: 'archive',
      categories: [],
      selectedDocs: [],
    },
  ],
  meta: {
    description:
      'Discover the latest insights, tips, and trends in health and wellness. Our diverse content covers articles, videos, podcasts, and more to help you live your healthiest life.',
    // @ts-ignore
    image: '{{IMAGE_1}}',
    title: 'Fixing Health Website',
  },
  title: 'Home',
}
